### ISSUE TITLE
Like icon/count change for response only visible to user who liked it

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#103]
Question likes are working perfectly, but I'm noticing a problem with Like icons/count for responses.

- Test Faculty likes a response by Test Student
- Test Faculty can see change in like/icon count
- Test Student sees that response has moved up to the top but no change appears in icon/count
- Other users also cannot see like/icon count change
- I tested this scenario with non-admin users doing the liking, and the behavior is the same. Admins don't see icon/count change when other users have liked responses.

### Test Faculty view just after liking response

![testfacultyview_tflike](https://user-images.githubusercontent.com/7189824/29320317-c6ec81c0-81a4-11e7-87e7-3fcb9c701b3a.png)

### Test Student view after Test Faculty liked response

![teststudentview_tflike](https://user-images.githubusercontent.com/7189824/29320349-e51dfb2e-81a4-11e7-888d-94fa4bf7415b.png)

Question URL: http://openlabdev.org/webwork-playground/#:problemId=local/ComplexFractions-Method2/single-binomial-easy.pg:questionId=11492

cc @moui72

**Comment by boonebgorges** [comment]
Hm, it looks like this has *always* been a bug - not new to the fall.

The root of the issue is that "like" counts returned from the server did not include responses, only questions. The reason why users were able to see their own likes is because the visible like counts are calculated: { other people's likes } + { my likes }; the latter data was available, while the former was not.

This is ready for testing.

**Comment by bree-z** [comment]
Thanks, Boone!  This looks good to me!
