### ISSUE TITLE
Course, section/faculty, and problem set filters only contain "Show All"

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#104]
The answer filter is fine.  I tested this before importing any new questions from WW, and also after I'd imported a few problems, with the same result.  I tried clearing my cache (a few times), and tried on Firefox, Chrome, and Safari.

![filtersempty](https://user-images.githubusercontent.com/7189824/29573776-d3cb8858-872d-11e7-867e-b446bb4c8729.png)

**Comment by boonebgorges** [comment]
Thanks for the details, @bree-z ! This is an odd problem that only crops up on the production site, because of the way that the client/server sites are configured there (on production, they're the same WP site, while on openlabdev they're different). I've just added a fix. Can you please verify the fix on production?

**Comment by bree-z** [comment]
Looks good, thanks!
