### ISSUE TITLE
'Home' link in menu should be blue

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#121]
It looks like the blue color is being overridden so that the 'Home' link in the menu is being styled as white.

![homelink](https://user-images.githubusercontent.com/7189824/40430902-d6889e7e-5eae-11e8-8d2e-1e239bdca03d.png)

![homelinkhover](https://user-images.githubusercontent.com/7189824/40431036-327bda66-5eaf-11e8-8e57-dfcf7331cf00.png)

**Comment by boonebgorges** [comment]
Thanks, Bree. As you can see, all styling on this page is messed up. It turns out that the problem was a missing `}` in the style.css stylesheet. I'm doing some weird voodoo to allow us to test the theme on openlabdev.org without also including the changes in the June release of the OpenLab, and it looks like I botched a merge. I've made the manual fix and it appears that things are now showing up properly - please do a hard refresh and look again.  (This should also fix the Upload Files styling items you mention at https://github.com/livinglab/webwork-for-wordpress/issues/107#issuecomment-391638782.)

**Comment by boonebgorges** [comment]
Good spot. This should now be fixed.

**Comment by bree-z** [comment]
Thanks Boone!  This is fixed, but it looks like the dropdown menu doesn't appear on hover.

**Comment by boonebgorges** [comment]
Blerg, the nightmare continues. I've just pushed a fix.

**Comment by bree-z** [comment]
Looks good, thanks!
