### ISSUE TITLE
Filter results: "No results found" overlaps with question metadata 

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#127]
When a search returns "No results found", the text overlaps with the question metadata.

<img width="823" alt="noresultsoverlap" src="https://user-images.githubusercontent.com/7189824/40842633-307cb8ca-65b7-11e8-988b-20066aae57ce.png">

**Comment by boonebgorges** [comment]
Thanks for the ticket! This resists a "proper" fix, where the header expands to fit the contents, because of some inner architectural issues (the 'Most Recent' dropdown is part of the "results" element, and so must move with it, so moving that whole thing down in the document has the result of putting the dropdown in a weird place). As a workaround, I've added a healthy padding to the top of the No Results message.

**Comment by bree-z** [comment]
Thanks, Boone!  Looks good on desktop and mobile.
