### ISSUE TITLE
iOS/Safari: WeBWorK-Dev doesn't send any identifying information

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#128]
Sorry, for not catching this earlier.  I tested this in Chrome and thought I'd tested in Safari too.  In Chrome (iOS) it's working fine, but in Safari there's no user or question information sent from WW-Dev:

- In WW-Dev, I click 'Ask for Help', e.g.: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/CoordinatePlaneTrig/3/?effectiveUser=student1&key=fdKoIiTsxNByq2LgwQPk3aARbF32ZmRq&user=student1
- If I'm already logged in I go directly to WW playground site, but just to the homepage: http://openlabdev.org/webwork-playground/
- If I'm not logged into OL dev, I'm asked to log in.

**Comment by boonebgorges** [comment]
Thanks, Bree. There are two issues here, both of which are tracked in #80.

1. On openlabdev.org, POST data doesn't come through the Ask for Help chain. This appears to be related to the HTTP authentication requirements on openlabdev.org. This means that course, problem set, etc is not received by WP.

2. Safari doesn't natively retain the URL fragment (the portion after `#`) in redirects. I built a workaround that stores the problem data in a cookie, and uses it to load the proper content in OL-WW. However, because of the POST problem in 1, the problem data is never received.

See especially https://github.com/livinglab/webwork-for-wordpress/issues/80#issuecomment-353484806 for more background. A closely related issue is https://discussions.apple.com/thread/8232508?answerId=8232508021#8232508021, though I can't find documentation on our precise issue from Safari/Apple.

As such, I'm fairly sure that this issue is limited to openlabdev.org, and that it's not new to this round of testing. (And it should probably be noted in the testing documentation.) The only way to confirm, as far as I can see, is to wait until after release.

**Comment by boonebgorges** [comment]
Bree, I'm going to move this into the next milestone. Could you have a test on the production site when you have a moment?

**Comment by bree-z** [comment]
Ack!  Sorry for never responding here!  This is working fine on the production site on iOS/Safari.
