### ISSUE TITLE
Display original problem on question discussion threads

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#2]
Andrew - you asked if this was "by design". I wouldn't glorify the decision by saying it was "design". But no, it's not a bug - I just never thought to put it there. It's not a particular problem to add it, though we'll need to have some general discussions about how much WW content to reproduce on the WP side, keeping in mind that WW content mirrored to WP will not be updated if the WW content is amended, and that the interactive answer fields on the WP side will have to be stripped because they'll be inoperable.

**Comment by drdrew42** [comment]
Exactly right. We don't want the answer fields to show, but I think we *do* want the actual problem to appear. Perhaps whenever an answer box is stripped, it could be replaced by underscore who's length matches the specified length of the input box. (or anything else that would indicate this is where WeBWorK wants a response - an image, or whatever)

The student asking the question should not need to re-type the problem out, and virtually none of them will understand TeX to make it look nice even if they did type it all out.

This means that anyone attempting to answer the question will not be able to see what problem the student is referring to. If the responder has access to WeBWorK, they'd specifically need access to the course in question - and it's quite a few steps of extra work required from them in order to see the problem.

**Comment by boonebgorges** [comment]
OK, I will figure something out.

**Comment by boonebgorges** [comment]
This is done.
