### ISSUE TITLE
replying to a question creates blank reply

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#30]
Trying to [reply to a question][1] as a faculty member or a student is currently not working for me. The content of my response field is not cleared, and an empty reply is generated.

Behavior noticed with Win7, Chrome 52+

http://openlabdev.org/webwork-playground/#/problem/local/AddRationalExpressions/diff-mono-easy.pg/question-11062

[1]: http://openlabdev.org/webwork-playground/#/problem/local/AddRationalExpressions/diff-mono-easy.pg/question-11062 "Question with blank replies"

**Comment by boonebgorges** [comment]
Can you check to see if there's anything in your JS console? When you 
refresh the page, has the response been posted?

**Comment by moui72** [comment]
> Can you check to see if there's anything in your JS console? 

I don't see anything relevant notably wrong but I am attaching the log for your perusal
[olwebwork.blankreply.jsconsole.txt](https://github.com/livinglab/webwork-for-wordpress/files/468178/olwebwork.blankreply.jsconsole.txt)


> When you refresh the page, has the response been posted?

Nope :( here's what I see
![blankreply](https://cloud.githubusercontent.com/assets/3885628/18449406/0792441e-78fd-11e6-8b1b-2445a9d4585e.png)

**Comment by boonebgorges** [comment]
Thank you for the additional details!

This break was due to some work I'd done to implement the Preview functionality. Previously, I'd been storing state for the question form and the response forms in different ways. Once I merged the code for rendering the two different form types, response form state was in limbo. I did some refactoring and things are working properly now.

Ready to test on openlabdev.org. Please be sure (here and always) to do a hard refresh before testing, as there's currently no cache versioning for scripts and styles on the test site.

**Comment by moui72** [comment]
this is fixed! I am not sure if you want me closing issues or not. let me know.

**Comment by boonebgorges** [comment]
> this is fixed! I am not sure if you want me closing issues or not. let me know.

If you opened it, and it looks fixed to you, then go ahead :)
