### ISSUE TITLE
question detail has multiple questions, titles are vacuous links

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#49]
I'm unsure of the intended functionality here, but I think it's currently a little confusing.

If I am looking at a question which is about a problem which also has other questions, all of that problem's questions will be visible. This seems reasonable.

The URLs for each question are different, and when loaded from a different page, will cause the view to scroll to the appropriate question, which makes sense.

e.g. the following urls render the same data but scroll to different questions
- http://openlabdev.org/webwork-playground/#/problem/local/ParabolaVertices/vertex-CtS-walkthrough.pg/question-11068
- http://openlabdev.org/webwork-playground/#/problem/local/ParabolaVertices/vertex-CtS-walkthrough.pg/question-11079

The question titles are links to these unique URLs, but the view does not change when they are clicked. This is a bit confusing.

I think that when the view is "maximally zoomed in" (that is, we're looking at the questions for a particular problem set) the question titles should no linker be styled as links

![clickabletitles](https://cloud.githubusercontent.com/assets/3885628/18926113/88c4e846-8584-11e6-9823-6cd7903e22fe.png)

**Comment by boonebgorges** [comment]
Heh, I was wondering whether anyone would notice this.

There's no scrolling when zoomed in all the way because, if you're clicking on the question title, then there's nowhere to scroll to :) But even in these cases, it's helpful to have a permalink to a question, in case you want to share that link with someone else. Maybe, when zoomed in all the way, the "A Question from..." text would *not* be a link, but it'd be followed by `#`, which *would* be a link? It's a bit awkward, but it's a convention I've seen used.

**Comment by moui72** [comment]
your reasoning makes sense to me -- we don't necessarily have to make a change. I mostly am just trying to think of ways to differentiate list views from detail views and this was one that I thought might work. I agree that having access to the permalink is necessary.

**Comment by boonebgorges** [comment]
I totally agree that it could be made clearer. Let's put this on a Jenna list and get some feedback.

**Comment by moui72** [comment]
"active question" is now highlighted with background color. this solves the issue for now.
